// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/KokoiRuby/rbac-based-management-system/backend/domain/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newApi(db *gorm.DB, opts ...gen.DOOption) api {
	_api := api{}

	_api.apiDo.UseDB(db, opts...)
	_api.apiDo.UseModel(&model.Api{})

	tableName := _api.apiDo.TableName()
	_api.ALL = field.NewAsterisk(tableName)
	_api.ID = field.NewUint(tableName, "id")
	_api.CreatedAt = field.NewTime(tableName, "created_at")
	_api.UpdatedAt = field.NewTime(tableName, "updated_at")
	_api.Name = field.NewString(tableName, "name")
	_api.Path = field.NewString(tableName, "path")
	_api.Method = field.NewString(tableName, "method")
	_api.Group_ = field.NewString(tableName, "group")

	_api.fillFieldMap()

	return _api
}

type api struct {
	apiDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	Name      field.String
	Path      field.String
	Method    field.String
	Group_    field.String

	fieldMap map[string]field.Expr
}

func (a api) Table(newTableName string) *api {
	a.apiDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a api) As(alias string) *api {
	a.apiDo.DO = *(a.apiDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *api) updateTableName(table string) *api {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.Name = field.NewString(table, "name")
	a.Path = field.NewString(table, "path")
	a.Method = field.NewString(table, "method")
	a.Group_ = field.NewString(table, "group")

	a.fillFieldMap()

	return a
}

func (a *api) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *api) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["name"] = a.Name
	a.fieldMap["path"] = a.Path
	a.fieldMap["method"] = a.Method
	a.fieldMap["group"] = a.Group_
}

func (a api) clone(db *gorm.DB) api {
	a.apiDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a api) replaceDB(db *gorm.DB) api {
	a.apiDo.ReplaceDB(db)
	return a
}

type apiDo struct{ gen.DO }

func (a apiDo) Debug() *apiDo {
	return a.withDO(a.DO.Debug())
}

func (a apiDo) WithContext(ctx context.Context) *apiDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a apiDo) ReadDB() *apiDo {
	return a.Clauses(dbresolver.Read)
}

func (a apiDo) WriteDB() *apiDo {
	return a.Clauses(dbresolver.Write)
}

func (a apiDo) Session(config *gorm.Session) *apiDo {
	return a.withDO(a.DO.Session(config))
}

func (a apiDo) Clauses(conds ...clause.Expression) *apiDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a apiDo) Returning(value interface{}, columns ...string) *apiDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a apiDo) Not(conds ...gen.Condition) *apiDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a apiDo) Or(conds ...gen.Condition) *apiDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a apiDo) Select(conds ...field.Expr) *apiDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a apiDo) Where(conds ...gen.Condition) *apiDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a apiDo) Order(conds ...field.Expr) *apiDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a apiDo) Distinct(cols ...field.Expr) *apiDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a apiDo) Omit(cols ...field.Expr) *apiDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a apiDo) Join(table schema.Tabler, on ...field.Expr) *apiDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a apiDo) LeftJoin(table schema.Tabler, on ...field.Expr) *apiDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a apiDo) RightJoin(table schema.Tabler, on ...field.Expr) *apiDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a apiDo) Group(cols ...field.Expr) *apiDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a apiDo) Having(conds ...gen.Condition) *apiDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a apiDo) Limit(limit int) *apiDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a apiDo) Offset(offset int) *apiDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a apiDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *apiDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a apiDo) Unscoped() *apiDo {
	return a.withDO(a.DO.Unscoped())
}

func (a apiDo) Create(values ...*model.Api) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a apiDo) CreateInBatches(values []*model.Api, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a apiDo) Save(values ...*model.Api) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a apiDo) First() (*model.Api, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Api), nil
	}
}

func (a apiDo) Take() (*model.Api, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Api), nil
	}
}

func (a apiDo) Last() (*model.Api, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Api), nil
	}
}

func (a apiDo) Find() ([]*model.Api, error) {
	result, err := a.DO.Find()
	return result.([]*model.Api), err
}

func (a apiDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Api, err error) {
	buf := make([]*model.Api, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a apiDo) FindInBatches(result *[]*model.Api, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a apiDo) Attrs(attrs ...field.AssignExpr) *apiDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a apiDo) Assign(attrs ...field.AssignExpr) *apiDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a apiDo) Joins(fields ...field.RelationField) *apiDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a apiDo) Preload(fields ...field.RelationField) *apiDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a apiDo) FirstOrInit() (*model.Api, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Api), nil
	}
}

func (a apiDo) FirstOrCreate() (*model.Api, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Api), nil
	}
}

func (a apiDo) FindByPage(offset int, limit int) (result []*model.Api, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a apiDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a apiDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a apiDo) Delete(models ...*model.Api) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *apiDo) withDO(do gen.Dao) *apiDo {
	a.DO = *do.(*gen.DO)
	return a
}
