// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Api             *api
	Menu            *menu
	Role            *role
	RoleMenuBinding *roleMenuBinding
	User            *user
	UserRoleBinding *userRoleBinding
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Api = &Q.Api
	Menu = &Q.Menu
	Role = &Q.Role
	RoleMenuBinding = &Q.RoleMenuBinding
	User = &Q.User
	UserRoleBinding = &Q.UserRoleBinding
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Api:             newApi(db, opts...),
		Menu:            newMenu(db, opts...),
		Role:            newRole(db, opts...),
		RoleMenuBinding: newRoleMenuBinding(db, opts...),
		User:            newUser(db, opts...),
		UserRoleBinding: newUserRoleBinding(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Api             api
	Menu            menu
	Role            role
	RoleMenuBinding roleMenuBinding
	User            user
	UserRoleBinding userRoleBinding
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Api:             q.Api.clone(db),
		Menu:            q.Menu.clone(db),
		Role:            q.Role.clone(db),
		RoleMenuBinding: q.RoleMenuBinding.clone(db),
		User:            q.User.clone(db),
		UserRoleBinding: q.UserRoleBinding.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Api:             q.Api.replaceDB(db),
		Menu:            q.Menu.replaceDB(db),
		Role:            q.Role.replaceDB(db),
		RoleMenuBinding: q.RoleMenuBinding.replaceDB(db),
		User:            q.User.replaceDB(db),
		UserRoleBinding: q.UserRoleBinding.replaceDB(db),
	}
}

type queryCtx struct {
	Api             *apiDo
	Menu            *menuDo
	Role            *roleDo
	RoleMenuBinding *roleMenuBindingDo
	User            *userDo
	UserRoleBinding *userRoleBindingDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Api:             q.Api.WithContext(ctx),
		Menu:            q.Menu.WithContext(ctx),
		Role:            q.Role.WithContext(ctx),
		RoleMenuBinding: q.RoleMenuBinding.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		UserRoleBinding: q.UserRoleBinding.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
