// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/KokoiRuby/rbac-based-management-system/backend/domain/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newRole(db *gorm.DB, opts ...gen.DOOption) role {
	_role := role{}

	_role.roleDo.UseDB(db, opts...)
	_role.roleDo.UseModel(&model.Role{})

	tableName := _role.roleDo.TableName()
	_role.ALL = field.NewAsterisk(tableName)
	_role.ID = field.NewUint(tableName, "id")
	_role.CreatedAt = field.NewTime(tableName, "created_at")
	_role.UpdatedAt = field.NewTime(tableName, "updated_at")
	_role.Name = field.NewString(tableName, "name")
	_role.UserList = roleManyToManyUserList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("UserList", "model.User"),
		RoleList: struct {
			field.RelationField
			UserList struct {
				field.RelationField
			}
			MenuList struct {
				field.RelationField
				ParentMenu struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("UserList.RoleList", "model.Role"),
			UserList: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("UserList.RoleList.UserList", "model.User"),
			},
			MenuList: struct {
				field.RelationField
				ParentMenu struct {
					field.RelationField
				}
				Children struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("UserList.RoleList.MenuList", "model.Menu"),
				ParentMenu: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("UserList.RoleList.MenuList.ParentMenu", "model.Menu"),
				},
				Children: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("UserList.RoleList.MenuList.Children", "model.Menu"),
				},
			},
		},
	}

	_role.MenuList = roleManyToManyMenuList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("MenuList", "model.Menu"),
	}

	_role.fillFieldMap()

	return _role
}

type role struct {
	roleDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	Name      field.String
	UserList  roleManyToManyUserList

	MenuList roleManyToManyMenuList

	fieldMap map[string]field.Expr
}

func (r role) Table(newTableName string) *role {
	r.roleDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r role) As(alias string) *role {
	r.roleDo.DO = *(r.roleDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *role) updateTableName(table string) *role {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.Name = field.NewString(table, "name")

	r.fillFieldMap()

	return r
}

func (r *role) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *role) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["name"] = r.Name

}

func (r role) clone(db *gorm.DB) role {
	r.roleDo.ReplaceConnPool(db.Statement.ConnPool)
	r.UserList.db = db.Session(&gorm.Session{Initialized: true})
	r.UserList.db.Statement.ConnPool = db.Statement.ConnPool
	r.MenuList.db = db.Session(&gorm.Session{Initialized: true})
	r.MenuList.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r role) replaceDB(db *gorm.DB) role {
	r.roleDo.ReplaceDB(db)
	r.UserList.db = db.Session(&gorm.Session{})
	r.MenuList.db = db.Session(&gorm.Session{})
	return r
}

type roleManyToManyUserList struct {
	db *gorm.DB

	field.RelationField

	RoleList struct {
		field.RelationField
		UserList struct {
			field.RelationField
		}
		MenuList struct {
			field.RelationField
			ParentMenu struct {
				field.RelationField
			}
			Children struct {
				field.RelationField
			}
		}
	}
}

func (a roleManyToManyUserList) Where(conds ...field.Expr) *roleManyToManyUserList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a roleManyToManyUserList) WithContext(ctx context.Context) *roleManyToManyUserList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a roleManyToManyUserList) Session(session *gorm.Session) *roleManyToManyUserList {
	a.db = a.db.Session(session)
	return &a
}

func (a roleManyToManyUserList) Model(m *model.Role) *roleManyToManyUserListTx {
	return &roleManyToManyUserListTx{a.db.Model(m).Association(a.Name())}
}

func (a roleManyToManyUserList) Unscoped() *roleManyToManyUserList {
	a.db = a.db.Unscoped()
	return &a
}

type roleManyToManyUserListTx struct{ tx *gorm.Association }

func (a roleManyToManyUserListTx) Find() (result []*model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a roleManyToManyUserListTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a roleManyToManyUserListTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a roleManyToManyUserListTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a roleManyToManyUserListTx) Clear() error {
	return a.tx.Clear()
}

func (a roleManyToManyUserListTx) Count() int64 {
	return a.tx.Count()
}

func (a roleManyToManyUserListTx) Unscoped() *roleManyToManyUserListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type roleManyToManyMenuList struct {
	db *gorm.DB

	field.RelationField
}

func (a roleManyToManyMenuList) Where(conds ...field.Expr) *roleManyToManyMenuList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a roleManyToManyMenuList) WithContext(ctx context.Context) *roleManyToManyMenuList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a roleManyToManyMenuList) Session(session *gorm.Session) *roleManyToManyMenuList {
	a.db = a.db.Session(session)
	return &a
}

func (a roleManyToManyMenuList) Model(m *model.Role) *roleManyToManyMenuListTx {
	return &roleManyToManyMenuListTx{a.db.Model(m).Association(a.Name())}
}

func (a roleManyToManyMenuList) Unscoped() *roleManyToManyMenuList {
	a.db = a.db.Unscoped()
	return &a
}

type roleManyToManyMenuListTx struct{ tx *gorm.Association }

func (a roleManyToManyMenuListTx) Find() (result []*model.Menu, err error) {
	return result, a.tx.Find(&result)
}

func (a roleManyToManyMenuListTx) Append(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a roleManyToManyMenuListTx) Replace(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a roleManyToManyMenuListTx) Delete(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a roleManyToManyMenuListTx) Clear() error {
	return a.tx.Clear()
}

func (a roleManyToManyMenuListTx) Count() int64 {
	return a.tx.Count()
}

func (a roleManyToManyMenuListTx) Unscoped() *roleManyToManyMenuListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type roleDo struct{ gen.DO }

func (r roleDo) Debug() *roleDo {
	return r.withDO(r.DO.Debug())
}

func (r roleDo) WithContext(ctx context.Context) *roleDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roleDo) ReadDB() *roleDo {
	return r.Clauses(dbresolver.Read)
}

func (r roleDo) WriteDB() *roleDo {
	return r.Clauses(dbresolver.Write)
}

func (r roleDo) Session(config *gorm.Session) *roleDo {
	return r.withDO(r.DO.Session(config))
}

func (r roleDo) Clauses(conds ...clause.Expression) *roleDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roleDo) Returning(value interface{}, columns ...string) *roleDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roleDo) Not(conds ...gen.Condition) *roleDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roleDo) Or(conds ...gen.Condition) *roleDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roleDo) Select(conds ...field.Expr) *roleDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roleDo) Where(conds ...gen.Condition) *roleDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roleDo) Order(conds ...field.Expr) *roleDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roleDo) Distinct(cols ...field.Expr) *roleDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roleDo) Omit(cols ...field.Expr) *roleDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roleDo) Join(table schema.Tabler, on ...field.Expr) *roleDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *roleDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roleDo) RightJoin(table schema.Tabler, on ...field.Expr) *roleDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roleDo) Group(cols ...field.Expr) *roleDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roleDo) Having(conds ...gen.Condition) *roleDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roleDo) Limit(limit int) *roleDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roleDo) Offset(offset int) *roleDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *roleDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roleDo) Unscoped() *roleDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roleDo) Create(values ...*model.Role) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roleDo) CreateInBatches(values []*model.Role, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roleDo) Save(values ...*model.Role) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roleDo) First() (*model.Role, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Role), nil
	}
}

func (r roleDo) Take() (*model.Role, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Role), nil
	}
}

func (r roleDo) Last() (*model.Role, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Role), nil
	}
}

func (r roleDo) Find() ([]*model.Role, error) {
	result, err := r.DO.Find()
	return result.([]*model.Role), err
}

func (r roleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Role, err error) {
	buf := make([]*model.Role, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roleDo) FindInBatches(result *[]*model.Role, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roleDo) Attrs(attrs ...field.AssignExpr) *roleDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roleDo) Assign(attrs ...field.AssignExpr) *roleDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roleDo) Joins(fields ...field.RelationField) *roleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roleDo) Preload(fields ...field.RelationField) *roleDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roleDo) FirstOrInit() (*model.Role, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Role), nil
	}
}

func (r roleDo) FirstOrCreate() (*model.Role, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Role), nil
	}
}

func (r roleDo) FindByPage(offset int, limit int) (result []*model.Role, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roleDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roleDo) Delete(models ...*model.Role) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roleDo) withDO(do gen.Dao) *roleDo {
	r.DO = *do.(*gen.DO)
	return r
}
