services:
  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      ENV: dev
      TLS_CERT: "/etc/tls/certs/gin.pem"
      TLS_KEY: "/etc/tls/certs/gin-key.pem"
    healthcheck:
      test: "curl -f http://localhost:8080/readiness || exit 1"
      interval: 20s
      timeout: 3s
      retries: 5
    networks:
      - rbac-be
    depends_on:
      consul:
        condition: service_healthy
      mysql:
        condition: service_healthy

  consul:
    build:
      context: ./..
      dockerfile: ./docker/consul/Dockerfile
    container_name: consul
    ports:
      # HTTP API and UI port
      - "8500:8500"
      # DNS interface port
      - "8600:8600/tcp"
      - "8600:8600/udp"
    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/health/state/passing"] # no curl in container
      test: "consul members | grep alive"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: always
    # sudo chown -R 1001:1001 ./docker/consul/data
    # https://hub.docker.com/r/bitnami/consul/
    volumes:
      - ./consul/data:/bitnami
    networks:
      - rbac-be

  mysql:
    build:
      context: ./..
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} $${MYSQL_DATABASE} -e 'SELECT 1'"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: always
    volumes:
      # MySQL automatically executes all .sql files in this directory during initialization only
      - ./../docker/mysql/fixtures:/docker-entrypoint-initdb.d
      # sudo chown -R 1001:1001 ./docker/mysql/data
      # https://hub.docker.com/r/bitnami/mysql
      # Remember to change back when run go mod tidy
      # sudo chown -R $USER:$USER ./docker/mysql/data
      - ./mysql/data:/bitnami/mysql/data
    networks:
      - rbac-be

networks:
  rbac-be:
    driver: bridge
